# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lG7aKMbhKvD3_cqbr7CzfW8HiqrDLen2
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

nombre_detectado = list(uploaded.keys())[0]
df = pd.read_csv(nombre_detectado)

df.head(5)