# -*- coding: utf-8 -*-
"""Demografia_Premios_Oscar_datos_limpios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_z8iI94KaFFfwn4g1f5BdCeKfE4qVVEH
"""

import pandas as pd

nombre_archivo = "Datos_limpios_Demografia_Premios_Oscar_1929-2026.csv"
df = pd.read_csv("Datos_limpios_Demografia_Premios_Oscar_1929-2026.csv")
df.head(5)