# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pMNurcGcFoGYwgGgv3YIJyhhyZ-ZUjX
"""

import pandas as pd

# Cargar la base de datos limpia desde tu archivo subido
df = pd.read_csv('base3_festivales_globos_bafta_y_berlin_completa (2).csv')

# Mostrar las primeras 10 filas de la tabla
df.head(10)